#!/usr/bin/env python3

from dependencies.dependencies import *
from dependencies.utils import *

DELAY_FETCHING_EMAILS = 10
DELAY_FETCHING_ERROR = 5

def monitor_incoming_emails():
    client = connectImap()
    client.select_folder('INBOX')
    print("En attente de nouveaux e-mails...")

    while True:
        try:
            new_emails = fetch_unread_emails(client)
            if new_emails:
                for email in new_emails:
                    logger(f"Nouveau message de {email['from']} : {email['subject']}", False)
                    sendMessageToDraft(client, subject=email['subject'], body=email['body'], recipient=email['from'])
                    saveEmailReceived(email, email['subject'], email['from'])
            time.sleep(DELAY_FETCHING_EMAILS)
        except KeyboardInterrupt:
            print("Arrêt de la surveillance.")
            break
        except Exception as e:
            logger(f"Erreur : {e}", True)
            time.sleep(DELAY_FETCHING_ERROR)

    client.logout()

if __name__ == "__main__":
    monitor_incoming_emails()
